### ISSUE TITLE
New controller configuration system

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2024#12]
This year's code changes including moving away from using raw button numbers on the controllers, and towards polling the buttons at meaningful positions on the controller (ex. bumper, trigger, ABXY buttons).

We want to avoid using the old system of checking which button numbers correspond to which physical button presses by abstracting this away into `AbstractController` and its subclasses.

Here is an example of some methods in `AbstractController`:
https://github.com/FRCteam3952/FRC2024/blob/c2d217a2f8058c4153e34cbd00aacfa9ebac1e93/src/main/java/frc/robot/controllers/AbstractController.java#L68-L119

However, we still want to have a centralized configuration file/class that can be easily located and accessed.

An example of this year's current setup is shown below:
https://github.com/FRCteam3952/FRC2024/blob/c2d217a2f8058c4153e34cbd00aacfa9ebac1e93/src/main/java/frc/robot/commands/IntakeCommand.java#L24-L37

Note how no constants or numbers are used - only direct calls to wrapped controller methods provided by `AbstractController`. While the use of these methods is preferred, the hard-coded buttons are not as they should be easier to locate around the codebase rather than locked in different files.

An example of the technique from previous years is shown below: (note the use of constants from the `Constants.ControllerConstants` class - these values are raw integers corresponding to raw button indices)
https://github.com/FRCteam3952/FRC2023/blob/73fec8fbcf24258c696e7088896c4645cfcf98d5/src/main/java/frc/robot/commands/clawcommands/ClawOpenandCloseCommand.java#L21-L33
```java
// Github decided not to embed the above link, so here's what that code looks like:
public void execute() {
    // System.out.println("CLAW TOGGLE: " + toggle);
    if (this.joystick.getRawButtonWrapper(ControllerConstants.CLAW_GRIP_OR_RELEASE_BUTTON_NUMBER) && toggle) {
        System.out.println("BUTTON PRESSED");
        // this.claw.setClawOpened(!this.claw.getClawClosed());
        if(this.claw.getClawClosed()) {
            this.claw.setClawOpened(false);
        } else {
            this.claw.setClawOpened(true);
        }
        toggle = false;
    }
    if (this.joystick.getRawButtonReleasedWrapper(ControllerConstants.CLAW_GRIP_OR_RELEASE_BUTTON_NUMBER)) {
        // ... method continues
```

We also would like to maintain a way to accomplish code similar to the following, but using the new controller code:
https://github.com/FRCteam3952/FRC2023/blob/73fec8fbcf24258c696e7088896c4645cfcf98d5/src/main/java/frc/robot/RobotContainer.java#L169-L172
```java
nintendoProController.controller.button(ControllerConstants.CALIBRATE_ARM_BUTTON_NUMBER).onTrue(new CalibrateArmPivotsCommand(arm, nintendoProController));
driverController.joystick.button(ControllerConstants.BALANCE_CHARGE_STATION_BUTTON_NUMBER).whileTrue(new BalanceChargeStationCommand(driveTrain));
nintendoProController.controller.button(ControllerConstants.FLIP_TURRET_BUTTON_NUMBER).onTrue(Commands.runOnce(() -> { // ... code continues
```

Again note the use of the constants, but also note that we are directly accessing the controller our class is specifically being used to wrap around - we want to avoid that and instead use the `AbstractController` methods.

The main goal of this issue is to:
* Maintain the new system found in `AbstractController`, with methods to abstract away determining which button is actually being checked/pressed. New methods may be added if necessary, but this should be unlikely.
* Implement a new system for configuring user input (i.e. which button presses correspond to which response from the robot)
* This system should have an easy process to determine which controller method should be called for a specific action.
* This system should have an easy process to modify which controller button corresponds to which action.
* This system should not rely on having a physical controller to figure out which button is which (i.e. the names of the methods in `AbstractController` should correspond to how the system handles buttons - `AbstractController#leftShoulderButton()` should correspond to a `LEFT_SHOULDER_BUTTON` or similar).

Ideally, using this system would look something like the following (adapting our current setup):
```java
if(ControlHandler.get(this.joystick, ControllerConstants.RUN_INTAKE_BUTTON)) { // code continues
```
However, the file names and syntax shown here don't need to be copied - you can go in a different path if you see fit.

Side note: the methods in `AbstractController` and the final code example return `Trigger`s, which are a part of the WPILIB library's controller support. Look into their documentation on this if necessary.

**Comment by siIverfish** [comment]
done thank you stanley
