### ISSUE TITLE
Set up AdvantageKit/AdvantageScope 

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2024#3]
Used for debugging/testing purposes

**Comment by ebay-kid** [comment]
https://github.com/Mechanical-Advantage/AdvantageKit (the (probably) more complicated one and the one we'd really like set up)

https://github.com/Mechanical-Advantage/AdvantageScope (simpler, a wrapper file to handle these uploads would be nice but not really required)

**Comment by foxinabox384** [comment]
Potentially installed AdvantageKit. I have no idea of how to debug or check if it is set up, so if the pull request goes through can someone check if I did it correctly?
