### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2024#8]
2 Motors (on CANSparkMax), one should be inverted from the other.
Motors should follow each other
Trigger power when button is pressed (button # TBD)

**Comment by ebay-kid** [comment]
More specific info:

* Two main intake motors in a top-down, one following the other (for consistency, make the top motor the "follower", and the bottom motor the "leader")
* One pivot motor to bring in the intake
* Assume a limit switch for calibration purposes (bringing intake in)
* Conveyor belt (one motor)

Basic requirements:

* Setting speed on all motors (note: for the two main intake motors, only one method is needed - this method should only set the speed on the motor designated as the "leader")
* Getter for the position of the pivot motor
* Method to set, and another to reset encoder on the pivot motor as well
* Getter on the limit switch value
* Make a class variable to store the PIDController on the integrated motor controller (cansparkmax) so we can position the pivot motor, no other motors need this. Please default the PID values to all 0, we can tune later
* Setter for the PIDController reference on the pivot (should take in an angle in degrees and send to the controller as a position ControlType)
* Getter for all three motor's currents (we're not sure which to use yet, just make a getter for all 3)

**Comment by siIverfish** [comment]
"avni is working on this" - avni

**Comment by ItsAvs** [comment]
finished code for intake, on separate branch; I was a little confused on the PID class variable so that may be incorrect
