### ISSUE TITLE
Shooter subsystem

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2024#9]
Info:
* Two main motors in a top-down configuration, one following the other. For consistency, make the top motor the "follower" and the bottom motor the "leader"
* One motor that pivots the shooter
* One motor for the flap on the shooter
* Assume 2 limit switches - one for pivot, one for flap

Basic requirements:
* Setting speed on all motors (note: for the two main shooter motors, only one method is needed - this method should only set the speed on the motor designated as the "leader")
* Getters for the positions of the pivot and shooter motors
* Methods to set, and reset, positions of the pivot and shooter motors
* Getters for the velocity of both (i.e. 2 methods) shooter motors
* Getter for each limit switch's value
* Make class variables to store the PIDController on the integrated motor controller (cansparkmax) so we can control all motors (for the two main motors, only control the "leader" motor). Please default the PID values to all 0, we can tune later
* Setters for the PIDController references on all controllers. For the pivot and flap, these should take in degrees. The one for the main motors can just take in an RPM

**Comment by foxinabox384** [comment]
hahaha, trying and failing

**Comment by ebay-kid** [comment]
Completed
